### ISSUE TITLE
Discuss layout

### ISSUE THREAD

**Issue by billiemj** [billiemj/webapp#3]
Please comment on your thoughts on layouts by 4/4
![Home Page](https://user-images.githubusercontent.com/11257976/55121232-8913c900-50c7-11e9-894e-7dfda4f5a687.jpg)
![Sign Up](https://user-images.githubusercontent.com/11257976/55121238-8e711380-50c7-11e9-8bc0-83fc034cecac.jpg)
![Add Media](https://user-images.githubusercontent.com/11257976/55121239-90d36d80-50c7-11e9-806e-06a52e73ba8c.jpg)

**Comment by sciencenerd** [comment]
A few things from me:

(1) What wireframe/mockup tool is this, and have we decided to use this tool as a group that this is the one we want to use going forward. I'm not saying this one is bad/good, I'm just asking for clarification so that we're all in agreement. 
(2) I think we should simplify the first screen in terms of the number of videos/preview screens. If we're just starting with the single media type (i.e., movies), perhaps it makes sense to have just a single preview available to stat with. 
(3) On the last panel, there's an "upload" option, but I'm not sure what the intention of this is.

**Comment by billiemj** [comment]
I am closing out the issue as I moved it to JiRA.
